In [2]:
import pandas as pd
import numpy as np
dataPath = "/media/cds/storage/DATA-1/hari/ResearchMethods/Module4_ResearchMethods/Data"

In [10]:
import os
files = sorted(os.listdir(dataPath))
for file in files:
    print(file, len(pd.read_csv(os.path.join(dataPath, file))))
    display(pd.read_csv(os.path.join(dataPath, file)))

Allocation_for_Welfare_of_Children-2021-2022.csv 144

,Category,Sl. No.,Ministry/Department,Scheme,2019-2020 Actuals,2020-2021 Budget Estimates,2020-2021 Revised Estimates,2021-2022 Budget Estimates
0,DemandNo. 3,1,Atomic Energy,Service Units,23.22,27.00,28.00,30.00
1,DemandNo. 3,2,Atomic Energy,Other Autonomous Bodies,119.56,133.27,132.51,138.10
2,DemandNo. 3,3,Atomic Energy,Atomic Research Centres,4.77,6.50,5.57,6.00
3,DemandNo. 3,NaN,Atomic Energy,Total :,147.55,166.77,166.08,174.10
4,DemandNo. 4,1,"Ministry of Ayurveda, Yoga and Naturopathy, Un...",Central Council for Research in Unani Medicine,NaN,NaN,1.00,1.20
...,...,...,...,...,...,...,...,...
139,DemandNo. 100,9,Ministry of Women and Child Development,Saksham Anganwadi and Poshan 2.0,NaN,NaN,NaN,19412.60
140,DemandNo. 100,10,Ministry of Women and Child Development,Mission Vatsalya,NaN,NaN,NaN,900.00
141,DemandNo. 100,NaN,Ministry of Women and Child Development,Total :,19853.30,25516.41,18384.64,20400.60
142,DemandNo. 101,1,Ministry of Youth Affairs and Sports,National Programme for Youth and Adolescent De...,20.28,23.00,20.00,21.00
143,Grand Total,Grand Total,Grand Total,Grand Total,80439.58,96042.43,80461.94,85712.56

Allocation_for_Welfare_of_Scheduled_Castes-2021-2022.csv 492

,Category,Sl. No.,Ministry/Department,Scheme,Actuals2019-2020 - Revenue,Actuals2019-2020 - Capital,Actuals2019-2020 - Total,Budget Estimates2020-2021 - Revenue,Budget Estimates2020-2021 - Capital,Budget Estimates2020-2021 - Total,Revised Estimates2020-2021 - Revenue,Revised Estimates2020-2021 - Capital,Revised Estimates2020-2021 - Total,Budget Estimates2021-2022 - Revenue,Budget Estimates2021-2022 - Capital,Budget Estimates2021-2022 - Total
0,DemandNo. 1,NaN,"Department of Agriculture, Cooperation and Far...",Total,12698.33,NaN,12698.33,22212.43,NaN,22212.43,19289.04,NaN,19289.04,20322.89,NaN,20322.89
1,DemandNo. 1,1,"Department of Agriculture, Cooperation and Far...",National Food Security Mission,213.48,NaN,213.48,343.08,NaN,343.08,304.91,NaN,304.91,378.20,NaN,378.20
2,DemandNo. 1,2,"Department of Agriculture, Cooperation and Far...",Organic Value Chain Development for North East...,2.51,NaN,2.51,29.01,NaN,29.01,29.01,NaN,29.01,29.01,NaN,29.01
3,DemandNo. 1,3,"Department of Agriculture, Cooperation and Far...",National Project on Soil Health and Fertility,16.76,NaN,16.76,53.25,NaN,53.25,28.00,NaN,28.00,53.25,NaN,53.25
4,DemandNo. 1,4,"Department of Agriculture, Cooperation and Far...",Rainfed Area Development and Climate Change,30.63,NaN,30.63,33.50,NaN,33.50,23.24,NaN,23.24,32.50,NaN,32.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,DemandNo. 101,328,Ministry of Youth Affairs and Sports,Assistance to Promotion of Sports Excellence,41.00,NaN,41.00,41.00,NaN,41.00,30.00,NaN,30.00,52.00,NaN,52.00
488,DemandNo. 101,328.01,Ministry of Youth Affairs and Sports,Assistance to National Sports Federations,41.00,NaN,41.00,41.00,NaN,41.00,30.00,NA,30.00,52.00,NaN,52.00
489,DemandNo. 101,329,Ministry of Youth Affairs and Sports,National Service Scheme,19.66,NaN,19.66,28.57,NaN,28.57,10.33,NaN,10.33,31.00,NaN,31.00
490,DemandNo. 101,330,Ministry of Youth Affairs and Sports,Khelo India,89.24,NaN,89.24,147.81,NaN,147.81,54.17,NaN,54.17,130.00,NaN,130.00
491,Grand Total,Grand Total,Grand Total,Grand Total,64848.26,349.12,65197.38,82830.62,426.0,83256.62,82582.51,125,82707.51,125804.20,455.0,126259.20

Allocation_for_Welfare_of_Scheduled_Tribe_2021-2022.csv 516

,Category,Sl.No.,Ministry/Department,Scheme,Actuals2019-2020 - Revenue,Actuals2019-2020 - Capital,Actuals2019-2020 - Total,Budget Estimates2020-2021 - Revenue,Budget Estimates2020-2021 - Capital,Budget Estimates2020-2021 - Total,Revised Estimates2020-2021 - Revenue,Revised Estimates2020-2021 - Capital,Revised Estimates2020-2021 - Total,Budget Estimates2021-2022 - Revenue,Budget Estimates2021-2022 - Capital,Budget Estimates2021-2022 - Total
0,DemandNo. 1,NaN,"Department of Agriculture, Cooperation and Far...",Total,8434.19,NaN,8434.19,11507.65,NaN,11507.65,9993.11,NaN,9993.11,10528.73,NaN,10528.73
1,DemandNo. 1,1,"Department of Agriculture, Cooperation and Far...",National Food Security Mission,204.85,NaN,204.85,218.92,NaN,218.92,192.50,NaN,192.50,186.20,NaN,186.20
2,DemandNo. 1,2,"Department of Agriculture, Cooperation and Far...",Organic Value Chain Development for North East...,63.82,NaN,63.82,63.01,NaN,63.01,63.01,NaN,63.01,63.01,NaN,63.01
3,DemandNo. 1,3,"Department of Agriculture, Cooperation and Far...",National Project on Soil Health and Fertility,8.01,NaN,8.01,27.24,NaN,27.24,11.00,NaN,11.00,27.24,NaN,27.24
4,DemandNo. 1,4,"Department of Agriculture, Cooperation and Far...",Rainfed Area Development and Climate Change,26.14,NaN,26.14,25.20,NaN,25.20,24.51,NaN,24.51,25.20,NaN,25.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511,DemandNo. 101,324,Ministry of Youth Affairs and Sports,Assistance to Promotion of Sports Excellence,21.50,NaN,21.50,21.50,NaN,21.50,10.00,NaN,10.00,29.00,NaN,29.00
512,DemandNo. 101,324.01,Ministry of Youth Affairs and Sports,Assistance to National Sports Federations,21.50,NaN,21.50,21.50,NaN,21.50,10.00,NA,10.00,29.00,NaN,29.00
513,DemandNo. 101,325,Ministry of Youth Affairs and Sports,National Service Scheme,15.39,NaN,15.39,14.84,NaN,14.84,7.94,NaN,7.94,16.00,NaN,16.00
514,DemandNo. 101,326,Ministry of Youth Affairs and Sports,Khelo India,48.08,NaN,48.08,76.57,NaN,76.57,31.80,NaN,31.80,66.00,NaN,66.00
515,NaN,Grand Total,NaN,Grand Total,44179.54,2731.93,46911.47,50136.73,3516.13,53652.86,49571.43,3732.54,53303.97,75398.45,4543.17,79941.62

Centrally_Sponsored_Schemes_2021-2022.csv 40

,Category,Sl.No.,Ministry/Department,Actuals2019-2020 - Revenue,Actuals2019-2020 - Capital,Actuals2019-2020 - Total,Budget Estimates2020-2021 - Revenue,Budget Estimates2020-2021 - Capital,Budget Estimates2020-2021 - Total,Revised Estimates2020-2021 - Revenue,Revised Estimates2020-2021 - Capital,Revised Estimates2020-2021 - Total,Budget Estimates2021-2022 - Revenue,Budget Estimates2021-2022 - Capital,Budget Estimates2021-2022 - Total
0,(A) Core of the Core Schemes,NaN,Total,93628.30,0.00,93628.30,85159.76,0.01,85159.77,165949.42,0.01,165949.43,96772.62,0.01,96772.63
1,(A) Core of the Core Schemes,1,Mahatma Gandhi National Rural Employment Guara...,71686.70,NaN,71686.70,61500.00,NaN,61500.00,111500.00,NA,111500.00,73000.00,NaN,73000.00
2,(A) Core of the Core Schemes,2,National Social Assistance Progam,8692.42,NaN,8692.42,9196.92,NaN,9196.92,42617.22,NA,42617.22,9200.00,NaN,9200.00
3,(A) Core of the Core Schemes,3,Umbrella Programme for Development of Minorities,1742.41,NaN,1742.41,1819.99,0.01,1820.00,1281.59,0.01,1281.60,1563.99,0.01,1564.00
4,(A) Core of the Core Schemes,4,Umbrella Programme for Development of Other Vu...,1711.28,NaN,1711.28,2210.00,NaN,2210.00,1675.00,NA,1675.00,2140.00,NaN,2140.00
5,(A) Core of the Core Schemes,5,Umbrella Programme for Development of Schedule...,4204.75,NaN,4204.75,4190.52,NaN,4190.52,3182.74,NA,3182.74,4303.01,NaN,4303.01
6,(A) Core of the Core Schemes,6,Umbrella Scheme for Development of Schedule Ca...,5590.74,NaN,5590.74,6242.33,NaN,6242.33,5692.87,NA,5692.87,6565.62,NaN,6565.62
7,(B) Core Schemes,NaN,Total,216424.41,29.90,216454.31,254203.12,55.75,254258.87,221657.58,65.71,221723.29,283802.52,69.09,283871.61
8,(B) Core Schemes,7,Rashtriya Swasthya Bima Yojna,3256.60,NaN,3256.60,6429.00,NaN,6429.00,3129.00,NA,3129.00,6401.00,NaN,6401.00
9,(B) Core Schemes,8,Blue Revolution,441.79,NaN,441.79,570.00,NaN,570.00,710.00,NA,710.00,1015.00,NaN,1015.00
10,(B) Core Schemes,9,Border Area Development Programme,824.59,NaN,824.59,783.71,NaN,783.71,50.00,NA,50.00,565.71,NaN,565.71
11,(B) Core Schemes,10,"Environment, Forestry and Wildlife",768.35,NaN,768.35,926.00,NaN,926.00,556.00,NA,556.00,766.00,NaN,766.00
12,(B) Core Schemes,11,Green Revolution,9881.25,13.65,9894.90,13269.45,50.32,13319.77,10414.16,59.34,10473.50,13352.19,56.00,13408.19
13,(B) Core Schemes,12,Infrastructure Facilities for Judiciary,990.00,NaN,990.00,762.00,NaN,762.00,599.00,NA,599.00,784.00,NaN,784.00
14,(B) Core Schemes,13,Jal Jeevan Mission (JJM)/National Rural Drinki...,10030.42,NaN,10030.42,11500.00,NaN,11500.00,11000.00,NA,11000.00,50011.00,NaN,50011.00
15,(B) Core Schemes,14,Jobs and Skill Development,5592.94,15.60,5608.54,5369.82,2.60,5372.42,3885.31,0.12,3885.43,3481.63,0.27,3481.90
16,(B) Core Schemes,15,Mission for Protection and Empowerment for Women,900.88,NaN,900.88,1163.00,NaN,1163.00,726.00,NA,726.00,48.00,NaN,48.00
17,(B) Core Schemes,16,Modernisation of Police Forces,4636.95,NaN,4636.95,3161.91,NaN,3161.91,1863.71,NA,1863.71,2803.11,NaN,2803.11
18,(B) Core Schemes,17,National Education Mission,33654.34,NaN,33654.34,39160.50,NaN,39160.50,28243.57,NA,28243.57,34300.16,NaN,34300.16
19,(B) Core Schemes,18,National Health Mission,35155.01,NaN,35155.01,34114.00,1.00,34115.00,35554.25,NA,35554.25,37125.30,5.00,37130.30
20,(B) Core Schemes,19,National Livelihood Mission - Ajeevika,9754.51,NaN,9754.51,10005.04,NaN,10005.04,10005.03,NA,10005.03,14472.61,NaN,14472.61
21,(B) Core Schemes,20,National Programme of Mid Day Meal in Schools,9699.00,NaN,9699.00,11000.00,NaN,11000.00,12900.00,NA,12900.00,11500.00,NaN,11500.00
22,(B) Core Schemes,21,Pradhan Mantri Awas Yojna (PMAY),24963.65,NaN,24963.65,27500.00,NaN,27500.00,40500.00,NA,40500.00,27500.00,NaN,27500.00
23,(B) Core Schemes,22,Pradhan Mantri Gram Sadak Yojna,14017.48,NaN,14017.48,19500.00,NaN,19500.00,13706.23,NA,13706.23,15000.00,NaN,15000.00
24,(B) Core Schemes,23,Pradhan Mantri Krishi Sinchai Yojna,8199.48,0.42,8199.90,11124.69,1.82,11126.51,7952.91,1.25,7954.16,11585.67,2.82,11588.49
25,(B) Core Schemes,24,Rashtriya Gram Swaraj Abhiyan(RGSA),465.16,NaN,465.16,857.53,NaN,857.53,564.76,NA,564.76,661.00,NaN,661.00
26,(B) Core Schemes,25,Shyama Prasad Mukherjee Rurban Mission,303.75,NaN,303.75,600.00,NaN,600.00,372.33,NA,372.33,600.00,NaN,600.00
27,(B) Core Schemes,26,Swachh Bharat Mission,1255.73,NaN,1255.73,2300.00,NaN,2300.00,1000.01,NA,1000.01,2300.00,NaN,2300.00
28,(B) Core Schemes,27,Swachh Bharat Mission (Gramin),8213.03,NaN,8213.03,9994.10,NaN,9994.10,6000.00,NA,6000.00,9994.10,NaN,9994.10
29,(B) Core Schemes,28,Umbrella ICDS,22031.43,0.23,22031.66,28557.37,0.01,28557.38,20033.31,5,20038.31,NaN,NaN,NaN
30,(B) Core Schemes,29,Urban Rejuvenation Mission: AMRUT and Smart Ci...,9598.68,NaN,9598.68,13750.00,NaN,13750.00,9850.00,NA,9850.00,13750.00,NaN,13750.00
31,(B) Core Schemes,30,White Revolution,1789.39,NaN,1789.39,1805.00,NaN,1805.00,1642.00,NA,1642.00,NaN,NaN,NaN
32,(B) Core Schemes,31,Rashtriya Pashudhan Vikas Yojana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NA,NaN,1177.04,NaN,1177.04
33,(B) Core Schemes,32,Mission Shakti (Mission for Protection and Emp...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NA,NaN,3109.00,NaN,3109.00
34,(B) Core Schemes,33,Mission VATSALYA (Child Protection Services an...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NA,NaN,900.00,NaN,900.00
35,(B) Core Schemes,34,Saksham Anganwadi and POSHAN 2.0 (Umbrella ICD...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NA,NaN,20100.00,5.00,20105.00
36,(B) Core Schemes,35,Prime Minister Formalisation of Micro Food Pro...,NaN,NaN,NaN,NaN,NaN,NaN,400.00,NA,400.00,500.00,NaN,500.00
37,(C) Others,NaN,Total,-529.93,0.00,-529.93,475.89,0.00,475.89,227.08,0,227.08,660.31,0.00,660.31
38,(C) Others,36,Others,-529.93,NaN,-529.93,475.89,NaN,475.89,227.08,NA,227.08,660.31,NaN,660.31
39,Grand Total,Grand Total,Grand Total,309522.78,29.90,309552.68,339838.77,55.76,339894.53,387834.08,65.72,387899.80,381235.45,69.10,381304.55

Corrected-Capital-Receipts-2021-22.csv 195

,Category,Sub-Category,Sl.No.,Tax Revenue,Major Head,Actuals 2019-2020,Budget 2020-2021,Revised 2020-2021,Budget 2021-2022
0,Non Debt Receipts,1. Recoveries of Loans & Advances,1.01,State Governments,NaN,NaN,NaN,NaN,NaN
1,Non Debt Receipts,1. Recoveries of Loans & Advances,1.01.01,Gross Receipts,7601,15550.89,12399.34,8957.13,8989.14
2,Non Debt Receipts,1. Recoveries of Loans & Advances,1.01.02,Recoveries,7601,NaN,-100.00,-100.00,-100.00
3,Non Debt Receipts,1. Recoveries of Loans & Advances,Net-State Governments,Net-State Governments,Net-State Governments,15550.89,12299.34,8857.13,8889.14
4,Non Debt Receipts,1. Recoveries of Loans & Advances,1.02,Union Territories (With Legislature),7602,72.00,100.00,100.00,100.00
...,...,...,...,...,...,...,...,...,...
190,Debt Receipts,9. Draw Down of Cash Balance,9.01,Receipts,9003,2729.02,2729.00,-2241.33,15116.81
191,Debt Receipts,9. Draw Down of Cash Balance,9.02,Disbursements,9003,2241.33,-55731.81,-15116.81,56266.05
192,Debt Receipts,Net-Draw Down of Cash Balance,Net-Draw Down of Cash Balance,Net-Draw Down of Cash Balance,Net-Draw Down of Cash Balance,4970.35,-53002.81,-17358.14,71382.86
193,Total-Debt Receipts,Total-Debt Receipts,Total-Debt Receipts,Total-Debt Receipts,Total-Debt Receipts,933650.40,796337.00,1848655.10,1506811.21
194,Grand Total,Grand Total,Grand Total,Grand Total,Grand Total,1002270.88,1021303.67,1895152.10,1694811.21

Corrected-Non-Tax-Revenue-2021-22_0.csv 162

,Category,Sub-Category,Sl. No.,Tax Revenue,Major Head,Actuals 2019-2020,Budget 2020-2021,Revised 2020-2021,Budget 2021-2022
0,"Interest Receipts, Dividends and Profits",1. Interest Receipt,1.01,States,'0049,7658.15,5313.20,3948.64,3813.15
1,"Interest Receipts, Dividends and Profits",1. Interest Receipt,1.02,Union Territories (With Legislature),'0049,37.85,60.02,59.02,59.02
2,"Interest Receipts, Dividends and Profits",1. Interest Receipt,1.03,Other Interest Receipts,'0049,49254.78,31968.82,51384.16,46613.47
3,"Interest Receipts, Dividends and Profits",1. Interest Receipt,1.03.01,Less-Receipts netted against expenditure,'0049,-44601.80,-26300.00,-41387.16,-38944.47
4,"Interest Receipts, Dividends and Profits",Net-Interest Receipt,Net-Interest Receipt,Net-Interest Receipt,Net-Interest Receipt,12348.98,11042.04,14004.66,11541.17
...,...,...,...,...,...,...,...,...,...
157,Grants-in-aid and Contribution,Total-Grants-in-aid and Contribution,Total-Grants-in-aid and Contribution,Total-Grants-in-aid and Contribution,Total-Grants-in-aid and Contribution,372.97,812.00,1421.75,747.00
158,Total-Grants-in-aid and Contribution,Total-Grants-in-aid and Contribution,Total-Grants-in-aid and Contribution,Total-Grants-in-aid and Contribution,Total-Grants-in-aid and Contribution,372.97,812.00,1421.75,747.00
159,Non Tax Revenue of Union Territories,9. Non Tax Revenue of Union Territories,9,9. Non Tax Revenue of Union Territories,1710,1761.81,2302.56,2080.63,2530.64
160,Non Tax Revenue of Union Territories,9. Non Tax Revenue of Union Territories,Total-Non Tax Revenue of Union Territories,Total-Non Tax Revenue of Union Territories,Total-Non Tax Revenue of Union Territories,1761.81,2302.56,2080.63,2530.64
161,Grand Total,Grand Total,Grand Total,Grand Total,Grand Total,327156.77,385017.30,210652.53,243027.90

Corrected-Tax-Revenue_2021-22.csv 119

,Category,Sl.No.,Tax Revenue,Major Head,Actuals 2019-2020,Budget 2020-2021,Revised 2020-2021,Budget 2021-2022
0,1. Corporation Tax,1.01,Collections,'0020,462842.68,589326.92,385961.53,473365.39
1,1. Corporation Tax,1.02,Surcharge,'0020,19054.14,65480.77,42884.62,52596.15
2,1. Corporation Tax,1.03,Education Cess / Health and Education Cess,'0020,20888.00,26192.31,17153.85,21038.46
3,1. Corporation Tax,1.04,Penalties,'0020,139.17,NaN,NaN,NaN
4,1. Corporation Tax,1.05,Interest Recoveries,'0020,1955.43,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
114,10. Less-NCCD transferred to the National Disa...,Net-Less-NCCD transferred to the National Disa...,Net-Less-NCCD transferred to the National Disa...,Net-Less-NCCD transferred to the National Disa...,-2480.00,-2930.00,-5820.00,-6100.00
115,11. Less-States' Share,11,11. Less-States' Share,'0710,-650677.05,-784180.87,-549988.35,-665562.74
116,12. Less-States' share adjustment as per Actual,12,11. Less-States' Share,'0710,NaN,NaN,29.16,NaN
117,Total-Tax Revenue,Total-Tax Revenue,Total-Tax Revenue,Total-Tax Revenue,1356902.28,1635909.13,1344500.64,1545396.53
118,Grand Total,Grand Total,Grand Total,Grand Total,1356902.28,1635909.13,1344500.64,1545396.53

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 9: invalid start byte